### PR TITLE
PR for Issue #6

### PR DESCRIPTION
**Pull request by daniel-swinehart**
HTML file with javascript file loaded in header is deployed to Netlify [HERE](https://daniel-issue6.netlify.app/).

Close Issue #6

### CODE REVIEW

**Comment by axecopfire** [comment]
I'm a bit confused here. This doesn't look like the design you built in issue 5.

**Comment by daniel-swinehart** [comment]
I have updated the html to match my new Figma design from issue #5. I am still working on an issue with the mobile version of my contact.html page though. Please offer any feedback.

**Comment by axecopfire** [comment]
- Image broken image
- I need to add [Lighthouse](https://developer.chrome.com/docs/lighthouse/overview/) to week 5
- Add your site logo and profile pic 
image
- That slide show can have the pics there loaded with descriptions and so when you do the slideshow feature you can already have it generally styled and all the content is there
- On the projects page what projects do you intend to add? Can you add them now instead of leaving a place holder?
- On the contact page each icon logo should have a background. It's hard to see the Linkedin one 
image
- Add the [Google Map](https://support.google.com/maps/answer/144361?hl=en&co=GENIE.Platform%3DDesktop) that you want instead of a placeholder

**Comment by daniel-swinehart** [comment]
Thanks for the feedback. Do you have any thoughts about how I set up the html structure with grid/flex? There were several times while I was working on it I thought I may be making things harder than they needed to be, but I wanted to finish what I had planned in my head to see it through.

**Review by axecopfire — APPROVED** [review]

**Pull request merged**
